### ISSUE TITLE
[KUDOS] Just a thank you ...

### ISSUE THREAD

**Issue by neurocis** [multiarch/crossbuild#14]
Forked at neurocis/docker-xbuilder, will be moving it to MXE as well as creating qt & mono/xamrin build containers based on this. Great work BTW, nice, succinct and simple. May port in to Alpine base image for ultimate light-weight.

Cheers!

**Comment by moul** [comment]
Thank you @neurocis, I just cherry-picked some commits from your fork (see #16) :)
